name: Extract GitHub Secret

on:
  workflow_dispatch:

jobs:
  extract-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Extract and Use Secret
      - name: Use the GitHub Secret
        run: |
          echo "Accessing the secret..."
          MY_EXTRACTED_SECRET="${{ secrets.SECRET }}"
          echo "The secret has been successfully retrieved."

      # Attempt to print (this will be masked)
      - name: Attempt to Print Secret
        run: echo "The extracted secret is $MY_EXTRACTED_SECRET"
