name: MLOps course first workflows
on: 
    push:
        branches:
          - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Sets up Python 3.8.
        uses: actions/setup-python@v2
        with: 
            python-version: 3.9
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
            pytest
